{% set name = "simage" %}
{% set version = "1.7.0" %}
{% set commit = "cf953eacd849" %}
{% set sha256 = "a214e75cfb1f20554c748578d4fdcca9bfaf004bc51e073cafe68b72b1a864a8" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://bitbucket.org/Coin3D/simage/get/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - disable_quicktime.patch

build:
    number: 1006
    skip: true  # [win and vc<14]

requirements:
    build:
        - ninja
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxfixes') }}  # [linux]
        - {{ cdt('libxcb') }}  # [linux]
        - {{ cdt('libxau') }}  # [linux]
        - {{ cdt('libxext') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
    host:
        - qt
        - libpng
        - jpeg
    run:
        - qt
        - libpng
        - jpeg

test:
    requires:
        - cmake  # [unix]
    files:
        - CMakeLists.txt  # [unix]
    commands:
        - where /r "%PREFIX%"  simage1.dll  # [win]

about:
    home: https://bitbucket.org/Coin3D/simage
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Simage, image-library needed by Coin3d.
    description: This is ``simage'', a library with image format loaders and front-ends
                 to common import libraries. simage is meant for use with applications
                 which reads image files as textures.
    doc_url: https://bitbucket.org/Coin3D/simage
    dev_url: https://bitbucket.org/Coin3D/simage

extra:
    recipe-maintainers:
        - looooo
