travis:
  secure:
    BINSTAR_TOKEN: SGsZvkACro3gaCoewe2p6Di95dQNAPv3TOmjf9c81oArOQb1wCUoKvAt9dfOM2kBFw/348kZDLhvLhjqaRyAamNCSRGO/BXidHkagsuxWJl/qhKPQKie/V+qvZ7sdi8djFcT57UBGHuKybainVyvZdKYp4NiH15wa6Ke0OTWUBJi90CJYe9tyxzvkvImhdBAUBj0Pvt6OgHAj3NjWPdltxvXaldEUtJqClNrHu7MhXuUwMFnlmMsjlm+l6QhRvBm7K/ru2FY1zGPSvCI55ZnqRzKnpMmY13xOoMhwa0p+7wVzrIp35dfat904xgAqEeyJuHVXRLYREuOt7YqfatE3ioIJwqFZtb+pVqvYuijfoZ1vTX/oyjf6X7E8og5jwWStk6KV4uIxGUYSYAGIGwmjpJdpTfZheYWyX7BNyJAgOEgl/1lWIZUv8uojWY/uHn2L9yTkVz/DDXSxmAyxSsPnu+gjEmlcxJsrJluiOVFrHLryPchaHpTJtPtnnbCNdydXaTi4LjDWT0K0bciDxXDyJyoT37PYVPUvlb90d19mXi0N2v8uPUGMUH1C4wgD5n5P4clbzaW2gEw7BVhadklO0g6lguIkF66CHrN6wAP9b1ta8JznhOOTOyQzQkxU3x0B6MpvOYIBD5V20D7AnGa7AQ6r1iE6jbyELWRzamkkWo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
    osx: circle