travis:
  secure:
    BINSTAR_TOKEN: EBtHDctrs1DOJlHIQerkWHo+qIJ8YmlfyuFNobTD5nZDRZgtm5axrR5UGYcXm3j/Cn5Q/7F8r29HdhRNpo6cmU8vyjTiDIvu/G91hLvRlpLhY/Y4tkbuE3f6BhW6syfDx/7/cexnvLknyNijD5EGikzXBJxGn2G8qOGZvJ1eNqiEpyV/IPW9zQpEjB+a6Ng1jtUrenBYfjYfgV3lq20vub7lMdTf3XMzWfSCvfwTLJGnT/8IjlXIyBXMvF31ITvUrFLS7UA7xrE9Mnwmt3TQzY+pGn3Wfpmg5r571nNaidv9eweacCaByMm4dvL0I1LLlZ5iqQu71ijFZlMnPVRHOQkBrY1bj+DEkrFW5xZLAbsFRdJErHVaKWkkpFRtZMwbSY1Y1OHt+bGmuueTQCQl3dFxoPQU15j2CO6wwSzbWXijwPWb6RL1F+2WICAF8JedO5q9QBLIrTMRtZ4QZ+BR3TrA6hBgZMXjv1DmHDscdwJJVjvAWoOEF7tBQxdvRolwWx7Oitr6OUU/WCMB0RWFi2b31nTCXOujuuHQ4yLhCsmX6+krCXC2aAnxMymxlujo+AC70As9shgjN9nzFDViuRcowpYizv47bdK6At8kUmJEYCe7O79VjnhUGPR8zS6Rf94d6FYIKMr7XHH6jRRm2ApwAnieVAtGEFXgUv6rMKA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: circle
